ent-ClothingHeadHelmetBase = { ent-ClothingHeadBase }
    .desc = { ent-ClothingHeadBase.desc }

ent-ClothingHeadHelmetBasic = шолом
    .desc = Звичайний обладунок охорони. Захищає голову від ударів.

ent-ClothingHeadHelmetMerc = шолом наймита
    .desc = Бойовий шолом часто використовується наймитами. Міцний, легкий і пахне, як порох та джунґлі.

ent-ClothingHeadHelmetSwat = шолом спецпризначенця
    .desc = Надміцний шолом, часто використовується парамілітарними силами. Цей має лоґо Nanotrasen на верхівці.

ent-ClothingHeadHelmetSwatSyndicate = шолом спецпризначенця
    .desc = Надміцний шолом, часто використовується парамілітарними силами. Цей прикрашений грізним червоно-чорним смугастим візерунком.
    .suffix = Синдикат

ent-ClothingHeadHelmetRiot = легкий шолом бунтівника
    .desc = Шолом, безпосередньо створений для захисту від ближніх ударів.

ent-ClothingHeadHelmetBombSuit = bombsuit helmet
    .desc = A heavy helmet designed to withstand the pressure generated by a bomb and any fragments the bomb may produce.

ent-ClothingHeadHelmetJanitorBombSuit = janitorial bombsuit helmet
    .desc = A heavy helmet designed to withstand explosions formed from reactions between chemicals.
    .suffix = DO NOT MAP

ent-ClothingHeadHelmetCult = шолом культу
    .desc = Міцний, зловіщий шолом культу.

ent-ClothingHeadHelmetSpaceNinja = space ninja helmet
    .desc = What may appear to be a simple black garment is in fact a highly sophisticated nano-weave helmet. Standard issue ninja gear.

ent-ClothingHeadHelmetTemplar = templar helmet
    .desc = DEUS VULT!

ent-ClothingHeadHelmetThunderdome = thunderdome helmet
    .desc = Let the battle commence!

ent-ClothingHeadHelmetWizardHelm = wizard helm
    .desc = Strange-looking helmet that most certainly belongs to a real magic user.

ent-ClothingHeadHelmetFire = fire helmet
    .desc = An atmos tech's best friend. Provides some heat resistance and looks cool.

ent-ClothingHeadHelmetAtmosFire = atmos fire helmet
    .desc = An atmos fire helmet, able to keep the user cool in any situation.

ent-ClothingHeadHelmetLing = chitinous helmet
    .desc = An all-consuming chitinous mass of armor.

ent-ClothingHeadHelmetERTLeader = ERT leader helmet
    .desc = An in-atmosphere helmet worn by the leader of a Nanotrasen Emergency Response Team. Has blue highlights.

ent-ClothingHeadHelmetERTSecurity = ERT security helmet
    .desc = An in-atmosphere helmet worn by security members of the Nanotrasen Emergency Response Team. Has red highlights.

ent-ClothingHeadHelmetERTMedic = ERT medic helmet
    .desc = An in-atmosphere helmet worn by medical members of the Nanotrasen Emergency Response Team. Has white highlights.

ent-ClothingHeadHelmetERTEngineer = ERT engineer helmet
    .desc = An in-atmosphere helmet worn by engineering members of the Nanotrasen Emergency Response Team. Has orange highlights.

ent-ClothingHeadHelmetERTJanitor = ERT janitor helmet
    .desc = An in-atmosphere helmet worn by janitorial members of the Nanotrasen Emergency Response Team. Has dark purple highlights.

ent-ClothingHeadHelmetRaid = syndicate raid helmet
    .desc = An armored helmet for use with the syndicate raid suit. Very stylish.

ent-ClothingHeadHelmetBone = bone helmet
    .desc = Cool-looking helmet made of skull of your enemies.

ent-ClothingHeadHelmetPodWars = ironclad II helmet
    .desc = An ironclad II helmet, a relic of the pod wars.

ent-ClothingHeadHelmetJustice = justice helm
    .desc = Advanced security gear. Protects the station from ne'er-do-wells.

ent-ClothingHeadHelmetJusticeEmpty = { ent-ClothingHeadHelmetJustice }
    .desc = { ent-ClothingHeadHelmetJustice.desc }
    .suffix = Empty

ent-ActionToggleJusticeHelm = Toggle Justice Helm
    .desc = Toggles the justice helm on and off.
